// This file is generated by Prismic local builder. Update with care!

export { default as AboutMe } from './AboutMe'
export { default as BannerSlice } from './BannerSlice'
export { default as Contact } from './Contact'
export { default as ServicesAndBenfits } from './ServicesAndBenfits'
export { default as Testimonials } from './Testimonials'
